version: '3.8'

services:
  blog:
    image: binbin-blog:${IMAGE_TAG:-latest}
    build:
      context: .
      args:
        GIT_SHA: ${GIT_SHA:-unknown}
    container_name: binbin-blog
    ports:
      - "80:80"
    restart: always
